[package]
name = "common-procedure"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common-error = { path = "../error" }
snafu.workspace = true
uuid.workspace = true
